file:
  upload:
    path: uploaded-files

spring:
  datasource:
    url: jdbc:mariadb://localhost:10001/junglim?characterEncoding=UTF-8&serverTimezsone=UTC
    username: junglim
    password: junglim9229
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
      default_batch_fetch_size: 1000
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: debug
    com.jedosa.junglim: debug
    com.querydsl.sql: debug
    org.springframework.orm.jpa: debug
    org.springframework.transaction: debug
    org:
      springframework:
        web: debug
